# Site Variables
title: IGDA Seattle
description: IGDA Seattle provides networking, learning, and speaker events to thousands of devs in Puget Sound’s thriving game industry.
ogImage: https://www.igdaseattle.org/images/logo-square.png
twitter: "@IGDASeattle"
footerCopy: IGDA Seattle is a local chapter of IGDA, a 501(c)(6) non-profit professional association. Questions? <a href="/about">Contact us</a>.

url: "" # TODO

# Build Settings
livereload: true
compress_html:
  clippings: all
  comments: all
