# Site Variables
title: IGDA Seattle
description: IGDA Seattle provides networking, learning, and speaker events to thousands of devs in Puget Sound’s thriving game industry.
url: https://www.igdaseattle.org
ogImage: https://www.igdaseattle.org/assets/images/logo-square.png
twitter: "@IGDASeattle"
footerCopy: IGDA Seattle is a local chapter of IGDA, a 501(c)(6) non-profit professional association. Questions? <a href="/about#contact">Contact us</a>.

# Build Settings
livereload: true
destination: ./dist
include: [
  "_pages",
]
exclude: [
  "Gemfile",
  "Gemfile.lock",
  "vendor",
  "node_modules",
  "package.json",
  "package-lock.json",
  "gulpfile.js",
  "assets/README.md",
  "README.md",
  "screenshot.jpg",
]
compress_html:
  clippings: all
  comments: all
